services:
    nginx:
        container_name: laravel-nginx
        image: nginx:1.23-alpine
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./src/public:/var/www/public
            - ./src/storage/app/public:/var/www/storage/app/public
        ports:
            - "${DOCKER_WEB_PORT}:80"

    php:
        container_name: laravel-php
        build: ./docker/php
        working_dir: /var/www
        volumes:
            - ./src:/var/www
        env_file:
           - .env
    
    mysql:
        container_name: laravel-mysql
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        ports:
            - "${DOCKER_MYSQL_PORT}:3306"